### ISSUE TITLE
QUESTION

### ISSUE THREAD

**Issue by chandu0211** [ShreyAmbesh/Traffic-Rule-Violation-Detection-System#15]
I have run the project and I'm getting a picture as an output. The picture displays a single vehicle which violated the traffic rule as given below. The speed is displayed as 3.8km/hr. I have run project in windows using anaconda.
![5](https://user-images.githubusercontent.com/46132286/60751485-3eadbc80-9fd3-11e9-88b1-8e6935811783.jpg)
I thought the project would display the speed of each and every vehicle passed by and take a picture of the vehicle which has violated the traffic rule.
What should I do in order to get video output which displays speed of every vehicle and recognize it's number plate

**Comment by ShreyAmbesh** [comment]
The speed is calculated for each vehicle But not displayed you can display the speed by tweaking the code a bit. You can even get License Plate Number of each Vehicle by calling openalpr API for each vehicle.
