### ISSUE TITLE
No module named 'object_detection'

### ISSUE THREAD

**Issue by kurzacz** [ShreyAmbesh/Traffic-Rule-Violation-Detection-System#16]
Hello,

I've downloaded your project, but I can't run it. I'm getting error:
```
Traceback (most recent call last):
  File "VehicleMoniter.py", line 40, in <module>
    from utils import label_map_util
  File "/home/asmox/AppDev/testing/Traffic-Rule-Violation-Detection-System/utils/label_map_util.py", line 22, in <module>
    from object_detection.protos import string_int_label_map_pb2
ModuleNotFoundError: No module named 'object_detection'
```
I suppose I need to install additional packages, or use BUILD file provided, but there is no mention in your README file. Can you please update your installation tutorial? I'm not able to use your library now

**Comment by Hahkarthick** [comment]
Follow these steps to run this application

1. Remove or move the  models folder 
2. Git clone this repo in your project dir (https://github.com/tensorflow/models)
3. Copy "models/research/object_detection"  object detection folder to root dir of your project
4. There you go !!!

**Comment by kurzacz** [comment]
Thank you, it helped me. I had to additionally compile models as described in:
https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/installation.md#protobuf-compilation

Reason: I was getting error like here:
https://github.com/tensorflow/models/issues/1595
