### ISSUE TITLE
Real time streaming

### ISSUE THREAD

**Issue by Sailor74** [ShreyAmbesh/Traffic-Rule-Violation-Detection-System#2]
Hi Shrey,
Great outcome well done. I have a question. Do you think your model would work with real time streaming as well? Say if we use a real time streaming youtube camera or similar. 
ozgur

**Comment by ShreyAmbesh** [comment]
> Hi Shrey,
> Great outcome well done. I have a question. Do you think your model would work with real time streaming as well? Say if we use a real time streaming youtube camera or similar.
> ozgur

I haven't tested it by I think it can work. You just have to change the video source on line 242 in VehicleMonitor.py to the incoming stream.
