### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by NayanDoshi** [ShreyAmbesh/Traffic-Rule-Violation-Detection-System#24]
Exception: 
 (402)
Reason: Payment Required
HTTP response headers: HTTPHeaderDict({'Access-Control-Allow-Headers': 'x-requested-with', 'Access-Control-Allow-Origin': '*', 'Content-Type': 'application/json; charset="utf-8"', 'Date': 'Sun, 01 Mar 2020 06:57:27 GMT', 'Server': 'nginx/1.10.3', 'Content-Length': '74', 'Connection': 'keep-alive'})
HTTP response body: {"error_code": 402, "error": "Monthly Usage (50) exceeded for this month"}

**Comment by ShreyAmbesh** [comment]
The error clearly mentions the reason. Open ALPR has a free usage quota and you have used it to use more you have to get the paid api
