### ISSUE TITLE
Secret Key  API from openALPR

### ISSUE THREAD

**Issue by NimishaHonnalli** [ShreyAmbesh/Traffic-Rule-Violation-Detection-System#27]
Could you please elaborate on how to fetch the key from OpenALPR? I have created an account.

**Comment by shreyanshu09** [comment]
> Could you please elaborate on how to fetch the key from OpenALPR? I have created an account.

Go to the OpenALPR website, log in, and enter the cloud API tab. You will see your secret key there.
