### ISSUE TITLE
How can I run offline openalpr

### ISSUE THREAD

**Issue by ChuongCS** [ShreyAmbesh/Traffic-Rule-Violation-Detection-System#3]
Hi Shrey Ambesh,

Thanks for your contribution. 
In your code, you use openalpr_api and connect to online server with secret key.
How can I modify your code to run offline?

Many thanks

**Comment by ShreyAmbesh** [comment]
You have to extract the license plate number(by training a model to detect license plates) and then run some OCR model like tesseract to extract the license plate number.
