### ISSUE TITLE
#No module name 'openalpr-api'

### ISSUE THREAD

**Issue by Sreejapalanivel** [ShreyAmbesh/Traffic-Rule-Violation-Detection-System#6]
I am working on this project 
 installed all the needed packages for the project but when i try to run the project in pycharm i am getting the following error...

File "VehicleMoniter.py", line 21, in 
import openalpr_api
ModuleNotFoundError: No module named 'openalpr_api'

I also installed openalpr in pycharm.
I don't know the issue. Please clarify me.

**Comment by ShreyAmbesh** [comment]
Can you reproduce the steps again in details so that I can try to find the issue ?

**Comment by utkarshyadav46** [comment]
ModuleNotFoundError: No module named 'openalpr_api'

**Comment by ShreyAmbesh** [comment]
Try to reinstall openalpr_api properly and if you have not set up the path variables properly check it.

**Comment by utkarshyadav46** [comment]
Sir ,
I had tried a lot even I install openalpr module but there were two problem
:
1. Tensorflow installation
2. Openalpr_api


Please help me so that I can work a little on this.
Waiting for your guidance

**Comment by ShreyAmbesh** [comment]
Can you please produce all your installation steps and the full error stack trace so that I can check the error. You can even try to see some online article or video to go through the installation process.

**Comment by Logeshkumar1595** [comment]
[openalpr_api.zip](https://github.com/ShreyAmbesh/Traffic-Rule-Violation-Detection-System/files/3039895/openalpr_api.zip)


Downlad openalpr_api.zip and place it 

> 
> 
> I am working on this project
> installed all the needed packages for the project but when i try to run the project in pycharm i am getting the following error...
> 
> File "VehicleMoniter.py", line 21, in
> import openalpr_api
> ModuleNotFoundError: No module named 'openalpr_api'
> 
> I also installed openalpr in pycharm.
> I don't know the issue. Please clarify me.

[openalpr_api.zip](https://github.com/ShreyAmbesh/Traffic-Rule-Violation-Detection-System/files/3039907/openalpr_api.zip)
Download above file and drag it to sitepackages folder

**Comment by EdwinAnyiwen** [comment]
Hi，sir，
According to your guide ，i have installed openALPR and api by"pip3 install openALPR api'',this installing was successful.but when i run "VehicleMoniter.py",there is a erro,it is "No module named 'openalpr_api'";

i think this module 'openalpr_api' is built by yourself, true or false??????

**Comment by SourabhMane** [comment]
[openalpr_api.zip](https://github.com/ShreyAmbesh/Traffic-Rule-Violation-Detection-System/files/3130612/openalpr_api.zip)
Download and paste this folder where VehicleMonitor.py resides.
This worked for me.
