### ISSUE TITLE
ImportError: Please upgrade your tensorflow installation to v1.4 or later!

### ISSUE THREAD

**Issue by Logeshkumar1595** [ShreyAmbesh/Traffic-Rule-Violation-Detection-System#8]
I've installed tensorflow 1.13.1, but I'm getting 'ImportError: Please upgrade your tensorflow installation to v1.4 or later!'

**Comment by danielkornev** [comment]
> I've installed tensorflow 1.13.1, but I'm getting 'ImportError: Please upgrade your tensorflow installation to v1.4 or later!'

simply remove the check or update to take versions bigger than 1.10 in to account
